[global]
market_channel = "md_channel"
data_folder = "../dat"
broker_id = "9999"
user_id = "userid"
password = "password"

[market]
front = "180.168.146.187:10131"
instruments = ["cu2311", "cu2312", "cu2401"]

[[strategy.stg]]
name = "logger"
libpath = "./bin/liblogger.so"
instruments = ["cu2311", "cu2312", "cu2401"]
accounts = ["test001"]
