data_folder = "./test/fixtures"
market_channel = "ctptrader_market_channel"

[ctpMG]
broker_id = "9999"
user_id = "123456"
password = "password"
market_front = "180.168.146.187:10131"
instruments = ["cu2311", "cu2312"]

[stgManager]

[[stgManager.stg]]
name = "logger"
libpath = "./bin/liblogger.so"